### ISSUE TITLE
Php error on second language after adding a block in first language

### ISSUE THREAD

**Issue by seb-celinedesign** [Daandelange/kirby-TranslatedLayout#1]
Panel error on second language after adding a block in first language : 
``array_key_exists(): Argument #2 ($array) must be of type array, null given in file: /Users/seb/Sites/proprietes.fr/site/plugins/translatedlayout/src/classes/TranslatedLayoutField.php line: 188``

**Comment by Daandelange** [comment]
Hey, thanks for the report.
That's weird because i've used an `@` to silent `array_key_exists` errors.
I'll try to digg it.
Anyways, the error should not prevent the plugin from working. :)

**Comment by Daandelange** [comment]
This was due to [the PHP8 stfu operator change](https://php.watch/versions/8.0/fatal-error-suppression). Fixed now ;)
