### ISSUE TITLE
Wrong Declaration of TranslatedLayoutField (Kirby 4.2)

### ISSUE THREAD

**Issue by andreasotto** [Daandelange/kirby-TranslatedLayout#8]
After installing this plugin:

```
Declaration of TranslatedLayoutField::fill($value = null) must be compatible with Kirby\Form\Field\LayoutField::fill(mixed $value = null): void
```

Is this plugin still valid for Kirby 4.2 ?

I absolutely miss this logic in Kirby, and can't understand why it's not the standard. I don't want to add the website structure for a second language from scratch, I just want to replace the content in the existing structure. I very much hope that there is a solution for this, e.g. in the form of this plugin?

**Comment by Daandelange** [comment]
Hi, I'm sorry, this plugin is for Kirby 3. (K4 is untested but only reading the breaking changes I know it will not be easy to port).
I was hoping so much to get this natively covered by Kirby4, they [are aware](https://forum.getkirby.com/t/multilanguage-content-synchronisation/23930) of [the feature request](https://kirby.nolt.io/234). A little before the K4 launch, they told me that they need too important changes under the hood to implement it properly and it's on an internal todo list together with some other features that need important changes. Let's hope it will come with K5 ! 

To me it really feels like «if you use multi-language, the coolest Kirby features simply disappear, so you better just not use multilanguage !». With only 14 upvotes in 3 years and only 2 forum user replies (_3 counting you!_), I guess most Kirby users simply don't care about true multi-language support.
